### ISSUE TITLE
Question: Why don't I see see all themes that are listed in the editor on npm or github?

### ISSUE THREAD

**Issue by dannief** [erming/resume-editor#16]
I am currently using the "[short](http://registry.jsonresume.org/#short)" theme and I would like to add some customization, but I can't find the source code anywhere. It is closed-source?

**Comment by erming** [comment]
Hey @dannief!

To answer your question: All themes are named like this: `jsonresume-theme-<theme_name>`

Our theme server automatically fetches repositories with the `jsonresume-theme-` prefix  from the npm repository. Look here: https://www.npmjs.com/jsonresume-theme-short

And here's the GitHub repository: https://github.com/isnotahippy/jsonresume-theme-short

_.. I just saw that this issue is 5 days old. Sorry for the wait._

**Comment by dannief** [comment]
Thanks! @erming 

I couldn't find it via the URL in the readme http://node-modules.com/search?q=jsonresume-theme-* or if I searched for jsonresume-theme-short in github
